"""empty message

Revision ID: 0db11c0ebba4
Revises: 6e3d535baab3
Create Date: 2021-08-03 16:15:07.194446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db11c0ebba4'
down_revision = '6e3d535baab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('interests', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('languages', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('nationality', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('occupation', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'occupation')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'languages')
    op.drop_column('user', 'interests')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'description')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
