"""empty message

Revision ID: 10b398bfbb01
Revises: 92e1c58a9d9e
Create Date: 2021-08-05 17:37:06.817300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b398bfbb01'
down_revision = '92e1c58a9d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_room_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_owner', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('id_tenant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_owner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_tenant'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_room_owner')
    # ### end Alembic commands ###
