"""empty message

Revision ID: 46c859e1a4a0
Revises: dde6b6f51a60
Create Date: 2021-08-16 18:29:59.735727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c859e1a4a0'
down_revision = 'dde6b6f51a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('lat', sa.Float(precision=7), nullable=True))
    op.add_column('room', sa.Column('lng', sa.Float(precision=7), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'lng')
    op.drop_column('room', 'lat')
    # ### end Alembic commands ###
