"""empty message

Revision ID: 75fa1f7bde5f
Revises: f0f676fbf1cf
Create Date: 2021-08-05 16:50:39.677098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fa1f7bde5f'
down_revision = 'f0f676fbf1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assesment_User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('interests', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('languages', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('nationality', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('occupation', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'occupation')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'languages')
    op.drop_column('user', 'interests')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'description')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    op.drop_table('Photo')
    op.drop_table('Assesment_User')
    # ### end Alembic commands ###
