"""empty message

Revision ID: fc1492e0b7d7
Revises: 0db11c0ebba4
Create Date: 2021-08-03 17:52:55.398443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1492e0b7d7'
down_revision = '0db11c0ebba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'interests',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'interests',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
